apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter '<head>' '<head>\n<base href="/k8s/grafana/">';
      sub_filter_once on;
    nginx.ingress.kubernetes.io/proxy-redirect-from: /login
    nginx.ingress.kubernetes.io/proxy-redirect-to: /k8s/grafana/login
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  generation: 2
  name: helo-prometheus-grafana
  namespace: prometheus
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: helo-prometheus-grafana
                port:
                  number: 80
            path: /grafana(/|$)(.*)
            pathType: Prefix
