apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - image: ts00328685/heloword-${APP_NAME}:${MAJOR_VERSION}.${MINOR_VERSION}
        name: ${APP_NAME}
        resources: {}
        env:
          - name: TZ
            value: Asia/Taipei
          - name: HELO_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: HELO_DB_USERNAME
          - name: HELO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: HELO_DB_PASSWORD
          - name: HELO_DB_URL
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: HELO_DB_URL
          - name: HELO_REDIS_URL
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: HELO_REDIS_URL
          - name: HELO_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: HELO_REDIS_PASSWORD
          - name: HELO_REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: HELO_REDIS_PORT
          - name: AES_KEY
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: AES_KEY
          - name: AES_IV
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: AES_IV
          - name: FEIGN_API_KEY
            valueFrom:
              secretKeyRef:
                name: heloword-secret
                key: FEIGN_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: ${APP_NAME}
status:
  loadBalancer: {}

