eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10

cipher:
  aes:
    key: ${AES_KEY}
    iv: ${AES_IV}

feign:
  api-key: ${FEIGN_API_KEY}
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 120000

spring:

  security:
    filter:
      order: 10

  datasource:
    url: ${HELO_DB_URL}
    username: ${HELO_DB_USERNAME}
    password: ${HELO_DB_PASSWORD}

  redis:
    host: ${HELO_REDIS_URL}
    password: ${HELO_REDIS_PASSWORD}
    port: ${HELO_REDIS_PORT}

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL55Dialect
      ddl-auto: update

  zipkin:
    # default false for local env
    enabled: false
    base-url: http://localhost:9411
